-- Programmers 131529 : 문자열
SELECT SUBSTR(PRODUCT_CODE, 1, 2) AS CATEGORY, COUNT(*) AS PRODUCTS
FROM PRODUCT
GROUP BY SUBSTR(PRODUCT_CODE, 1, 2)
ORDER BY CATEGORY

SELECT CATEGORY, COUNT(CATEGORY) AS COUNT
FROM 
    (SELECT SUBSTR(PRODUCT_CODE, 0, 2) AS CATEGORY
    FROM PRODUCT)
GROUP BY CATEGORY
ORDER BY CATEGORY
