-- Programmers 144854 : JOIN
SELECT BOOK.BOOK_ID, AUTHOR.AUTHOR_NAME, TO_CHAR(BOOK.PUBLISHED_DATE, 'YYYY-MM-DD') PUBLISHED_DATE
FROM BOOK JOIN AUTHOR
ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
WHERE BOOK.CATEGORY IN ('경제')
ORDER BY PUBLISHED_DATE ASC


SELECT BOOK.BOOK_ID, AUTHOR.AUTHOR_NAME, TO_CHAR(BOOK.PUBLISHED_DATE, 'YYYY-MM-DD') PUBLISHED_DATE
FROM BOOK, AUTHOR
WHERE BOOK.CATEGORY IN ('경제') 
      AND BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
ORDER BY PUBLISHED_DATE ASC


