-- Programmers 59412 : 문자열, Date, GROUP BY, 숫자 변환
-- 시간형식 HH24 주의
SELECT HOUR, COUNT(HOUR) AS COUNT
FROM 
    (SELECT TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) AS HOUR
    FROM ANIMAL_OUTS)
WHERE HOUR >= 9 AND HOUR < 20
GROUP BY HOUR
ORDER BY HOUR
