-- Programmers 131123 : GROUP BY
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO
WHERE (FOOD_TYPE, FAVORITES) IN 
    (SELECT FOOD_TYPE, MAX(FAVORITES)
    FROM REST_INFO
    GROUP BY FOOD_TYPE)
ORDER BY FOOD_TYPE DESC

-- JOIN 사용
SELECT A.FOOD_TYPE, A.REST_ID, A.REST_NAME, A.FAVORITES
FROM REST_INFO A
INNER JOIN
    (SELECT FOOD_TYPE, MAX(FAVORITES) AS MAX_FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE) B
ON A.FOOD_TYPE = B.FOOD_TYPE AND A.FAVORITES = B.MAX_FAVORITES
ORDER BY A.FOOD_TYPE DESC

-- KEEP (DENSE_RANK FIRST ORDER BY...) 실습
SELECT FOOD_TYPE, 
        MAX(REST_ID) KEEP(DENSE_RANK FIRST ORDER BY FAVORITES DESC) AS REST_ID,
        MAX(REST_NAME) KEEP (DENSE_RANK FIRST ORDER BY FAVORITES DESC) AS REST_NAME,
        MAX(FAVORITES) AS MAX_FAVORITES
FROM REST_INFO
GROUP BY FOOD_TYPE
ORDER BY FOOD_TYPE DESC
