-- Programmers 144855 : 집계함수_SUM, GROUP BY, JOIN
SELECT B.CATEGORY, SUM(S.SALES) AS TOTAL_SALES
FROM BOOK B 
INNER JOIN BOOK_SALES S ON B.BOOK_ID = S.BOOK_ID
WHERE TO_CHAR(S.SALES_DATE, 'YYYY-MM') = '2022-01'
GROUP BY CATEGORY
ORDER BY CATEGORY ASC
