-- Programmers 164671 : String, Date
SELECT '/home/grep/src/'||BOARD_ID||'/'||FILE_ID||FILE_NAME||FILE_EXT AS FILE_PATH
FROM  USED_GOODS_FILE
WHERE BOARD_ID IN (SELECT MAX(BOARD_ID) KEEP (DENSE_RANK FIRST ORDER BY VIEWS DESC) AS BOARD_ID
            FROM USED_GOODS_BOARD) 
ORDER BY FILE_ID DESC
