-- Programmers 164670 : String, Date, JOIN, GROUP BY
SELECT U.USER_ID
       , U.NICKNAME
       , (CITY||' '||STREET_ADDRESS1||' '||STREET_ADDRESS2) AS 전체주소
       , SUBSTR(U.TLNO, 1, 3) || '-' || SUBSTR(U.TLNO, 4, 4) || '-' || SUBSTR(U.TLNO, 8, 4) AS 전화번호
FROM USED_GOODS_USER U
INNER JOIN (SELECT WRITER_ID FROM USED_GOODS_BOARD GROUP BY WRITER_ID HAVING COUNT(BOARD_ID) >= 3) B
ON B.WRITER_ID = U.USER_ID
ORDER BY U.USER_ID DESC
