-- Programmers 59045 : JOIN, String
SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
FROM ANIMAL_INS I
INNER JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.SEX_UPON_INTAKE LIKE '%Intact%' 
    AND REGEXP_LIKE(O.SEX_UPON_OUTCOME, 'Spayed|Neutered')
ORDER BY I.ANIMAL_ID ASC
