-- Programmers 59411 : JOIN
SELECT ANIMAL_ID, NAME
FROM 
    (SELECT I.ANIMAL_ID AS ANIMAL_ID, I.NAME AS NAME, O.DATETIME - I.DATETIME AS DURATION
    FROM ANIMAL_INS I
    INNER JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
    ORDER BY DURATION DESC)
WHERE ROWNUM < 3
